"""rename address

Revision ID: 3d227cfdeab5
Revises: ab4e57f0ca27
Create Date: 2024-06-09 20:21:15.146426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d227cfdeab5'
down_revision = 'ab4e57f0ca27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name='location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name='address')

    # ### end Alembic commands ###
