"""rename department

Revision ID: ab4e57f0ca27
Revises: ae4d6071f8b4
Create Date: 2024-06-09 20:17:31.275764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab4e57f0ca27'
down_revision = 'ae4d6071f8b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("department", 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
